### ISSUE TITLE
Inconsistent behavior with Play Store updates

### ISSUE THREAD

**Issue by cburschka** [Genymobile/gnirehtet#37] opened 2017-07-25 09:34 UTC
Not sure if this is a bug in the Play Store, but I generally find that updates can't be downloaded if wifi and data are both turned off. Instead of using the relay, the app will claim there is no connection available.

Briefly enabling the mobile data connection makes it work, and thereafter I can disable it again to download the updates via gnirehtet...

**Comment by rom1v** [comment] 2017-07-25 10:21
Yes, some apps (including PlayStore, apparently) only check whether there is wifi or mobile data, but not any kind of connectivity.

**Comment by gilcu3** [comment] 2017-08-17 12:31
Sorry if I'm writing offtopic, but this behaviour is exactly what I get in my nexus 5 with AOSP 7.1. On the other hand, recently I have seen (unexpectedly) something different, with a Samsung Galaxy J2 Prime, stock android 6.0.1, and even without data nor wifi on all apps go through gnirehtet (play store, google apps, everything...). So I ask, is there any log I could get from the samsung phone so that to clarify why does it work there and then try to port it for everyone else?

**Comment by rom1v** [comment] 2017-08-17 14:28
The problem is probably related to [`setAsUnderlyingNetwork()`](https://github.com/Genymobile/gnirehtet/blob/736aff8680ab26c0578d2d77886df22959bfc057/app/src/main/java/com/genymobile/gnirehtet/GnirehtetService.java#L135-L160).

@gilcu3 If you know how to dev on Android, maybe you could check its behavior on your devices?

**Comment by gilcu3** [comment] 2017-08-17 14:31
Sorry @rom1v I'm don't know how to dev on Android, I could follow steps if you provide them though, I have basic knowledge on java, adb, linux...

**Comment by godofrayer** [comment] 2017-08-18 09:16
Its good enough to turn on your mobile data, even though your phone using gnirehtet. Your data wont reduce even you turn it on

**Comment by gilcu3** [comment] 2017-08-18 11:44
I know, and being rooted I can even do fancy stuff as automating the process. But what if there is no coverage or I have no sim, (and have no hotspot available)? Those situations are indeed happening sometimes :|

**Comment by rom1v** [comment] 2017-08-25 11:47
On the devices where Play Store does not work correctly with gnirehtet, does [this page](https://chris.bolin.co/offline/) appear as offline or online?

**Comment by gilcu3** [comment] 2017-08-25 11:59
I loaded the page using chrome, and it shows:

> You must go offline to view this page.
> Enable airplane mode.

I enabled airplane mode, and it shows the same. So it appears online. Anyway chrome can open any page through gnirehtet, only apps like Inbox and Play Store don't work

**Comment by gilcu3** [comment] 2017-09-05 15:14
@rom1v 
Today the Play Store app updated to version 8.1.73.S-all [0] [FP] 165518514, and now I get internet in the play store through gnirehtet, working perfectly :)

**Comment by rom1v** [comment] 2017-09-05 15:29
Great 👍

This shows that it is a problem in the applications themselves, so I'm closing this issue.

**Closed by rom1v** 2017-09-05 15:29 UTC

**Comment by rom1v** [comment] 2018-08-24 08:50
> Hi just wondering if you could close another 5 topics

If more duplicates are posted, yes, I will close them as duplicate.

> how the hell this project is supposed to be issued will know as a genuine fact that you have no interest in having a usable project here

Do you talk about the Google Play issue?

> How about being absolutely no help whatsoever. Thank you

You're welcome.

**Comment by qdeeds76** [comment] 2018-08-26 19:44
That wasn't my proudest moment.  Appreciate your humor.  Believe it or not I've been sober for awhile but, I guess I can still be a little....irrational...when tired and crabby.  Still working on that self-awareness thing, obviously.

I'll be honest it feels good knowing I was sober and can't just like shrug and be like "um, I'm an asshole when I'm drunk ad nauseum x 1000 times" and yep that was just me being a kinda whiney bitch who should have hung it up a few hours earlier.

**Comment by rafa9101** [comment] 2018-12-03 17:52
I just activated Mobile Data and solved the problem, installing the apks from google play with gnirehtet!!!!

**Comment by amosbird** [comment] 2019-02-14 16:27
@rom1v This issue seems to have other implications. Does gnirehtet setup VPN connection different than other apps ( e.g. https://github.com/itrump/shadowsocksRss/tree/master/android) ?

Play Store works as expected with those VPN apps except gnirehtet. All downloads are pending for a network connection. However, if a download is already running, switching to gnirehtet VPN works fine.

All these are tested on a Xiaomi6 phone with MIUI 10 9.1.24, Android 8

There is also a related issue. When opening netease-music without logging in, under gnirehtet network, it says "there is no network available", however after logging in, it works fine.  (it's a Chinese spotify-like app https://www.coolapk.com/apk/com.netease.cloudmusic )

**Comment by rom1v** [comment] 2019-02-14 16:39
@amosbird 

If you want to investigate, you could compare:
 - https://github.com/yeweishuai/shadowsocksr-android/blob/ad7af09df3421a2b8c159734a5834d9714ef1613/src/main/scala/com/github/shadowsocks/ShadowsocksVpnService.scala#L336
 - https://github.com/Genymobile/gnirehtet/blob/v2.3/app/src/main/java/com/genymobile/gnirehtet/GnirehtetService.java#L113

At first glance, I don't see any obvious difference that could explain that is works on ShadowSocksR but not in Gnirehtet.

**Comment by amosbird** [comment] 2019-02-14 17:06
@rom1v thanks. Comparing to ssr I removed `        // setAsUndernlyingNetwork();` and it works as expected

**Comment by amosbird** [comment] 2019-02-14 17:08
netease-music works fine too

**Comment by rom1v** [comment] 2019-02-14 20:40
> Comparing to ssr I removed `setAsUnderlyingNetwork();` and it works as expected

This is surprising, because the purpose of `setAsUnderlyingNetwork();` was to make the application aware of connectivity. When I implemented it, it worked better with than without for many applications.

https://github.com/Genymobile/gnirehtet/commit/c99b1a7620c0cada91799f141560e5ada04c2ec8#diff-10904a1cf9037d4d44f3e5f5c7e492c8R75

**Comment by Biswa96** [comment] 2020-01-23 07:28
gnirehtet + Google PlayStore works well with Nokia 4.2 Android 9. But in Xiaomi MIUI based devices, PlayStore does not download a bit while installing & updating a package, other applications work well.

**Comment by simonferndriger** [comment] 2021-02-20 05:23
What is the point of Gnirethtet, when major Apps do not work with it? Wouldn't it make more sense to collaborate with the Anroid developers?

**Comment by tvinki899** [comment] 2021-03-18 12:15
> 
> 
> > Comparing to ssr I removed `setAsUnderlyingNetwork();` and it works as expected
> 
> This is surprising, because the purpose of `setAsUnderlyingNetwork();` was to make the application aware of connectivity. When I implemented it, it worked better with than without for many applications.
> 
> [c99b1a7#diff-10904a1cf9037d4d44f3e5f5c7e492c8R75](https://github.com/Genymobile/gnirehtet/commit/c99b1a7620c0cada91799f141560e5ada04c2ec8#diff-10904a1cf9037d4d44f3e5f5c7e492c8R75)

can someone give patched files or something for beginers who cant build it

**Comment by LeeBinder** [comment] 2022-02-04 02:34
> > > Comparing to ssr I removed `setAsUnderlyingNetwork();` and it works as expected
> > 
> > 
> > This is surprising, because the purpose of `setAsUnderlyingNetwork();` was to make the application aware of connectivity. When I implemented it, it worked better with than without for many applications.
> > [c99b1a7#diff-10904a1cf9037d4d44f3e5f5c7e492c8R75](https://github.com/Genymobile/gnirehtet/commit/c99b1a7620c0cada91799f141560e5ada04c2ec8#diff-10904a1cf9037d4d44f3e5f5c7e492c8R75)
> 
> can someone give patched files or something for beginers who cant build it

may I kindly second this request

**Comment by OP4LIFE** [comment] 2022-02-24 11:39
Greetings.

A workaround for the apps that do not work:
Condition: You must have at least 2G network available.

1. In network settings, set the "Preferred network type" to 2G/3G
(If this option is not in the settings, call \*#\*#4636#\*#\*, click on Phone information and set Preferred network type to "GSM only".)

2. Optional (to prevent any data usage): Block apps' access to mobile connection in the settings.
In Android 11: Settings > Apps & Notifications > YouTube (an example app) > Mobile data & Wi-Fi > Enable mobile connection (turn off this option). For me there is also a quicker way to disable all apps' network access at once via so called Mobile manager; this may differ from phone to phone, though.

I thank all developers and contributors for this program.

Regards,
Matej
\
\
References: [Preferred Network Types Explained](https://forum.xda-developers.com/t/2g-3g-3-5g-preferred-network-types-explained-how-to-change-it-easily.966172/)

**Comment by LeeBinder** [comment] 2022-02-24 20:23
@OP4LIFE neat, thank you - will test asap. Which ROM do you use, or if stock, with which phone have you tested this?

**Comment by OP4LIFE** [comment] 2022-02-24 23:02
The original comment is now updated and includes device details.

**Comment by isarrider** [comment] 2023-10-11 14:33
> @rom1v thanks. Comparing to ssr I removed `setAsUndernlyingNetwork();` and it works as expected

maybe a switch then passed a command line would make sense here?

**Comment by Keiser04** [comment] 2024-04-04 21:23
> Greetings.
> 
> A workaround for the apps that do not work: Condition: You must have at least 2G network available.
> 
> 1. Turn on mobile data.
> 2. In network settings, set the "Preferred network type" to 2G/3G.
>    (If this option is not in the settings, call *#*#4636#*#*, click on Phone information and set Preferred network type to "GSM only".)
> 3. Optional (to prevent any data usage): Block apps' access to mobile connection in the settings.
>    For Android 11: Settings > Apps & Notifications > YouTube (an example app) > Mobile data & Wi-Fi > Enable mobile connection (turn off this option). For me there is also a quicker way to disable all apps' network access at once via so called Mobile manager; this may differ from phone to phone, though.
> 
> It is also possible to skip the 2. step and do the third step for all apps. I thank all developers and contributors for this program.
> 
> Regards, Matej Device details: ZenFone 8, Android 11, stock References: [Preferred Network Types Explained](https://forum.xda-developers.com/t/2g-3g-3-5g-preferred-network-types-explained-how-to-change-it-easily.966172/)

not working in tiktok
