### ISSUE TITLE
Permission denied problem on Redmi Note3 Android 6.0.1

### ISSUE THREAD

**Issue by Meowzz95** [Genymobile/gnirehtet#53] opened 2017-10-25 08:46 UTC
The phone client won't start when the server on PC is on and calling the START intent, the info in logcat shows that system has denied the broadcasting intent. During this process, no prompt asks for permission on phone side.

I guess there's some permission checking and granting requesting need to be done in the android client?

Here's the logcat output.

`
10-25 16:35:29.436  2739  2757 D com.android.server.pm.PackageManagerServiceInjector: MIUILOG- permissionπÇÇdenied android.permission.WRITE_SECURE_SETTINGS
`
`
10-25 16:35:29.436  2739  2757 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.genymobile.gnirehtet.START flg=0x10 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver } from null (pid=15564, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS due to receiver com.genymobile.gnirehtet/.GnirehtetControlReceiver
10-25 16:35:29.438 15564 15564 D AndroidRuntime: Shutting down VM
`

Thanks!

**Comment by rom1v** [comment] 2017-10-25 08:50
Duplicate of https://github.com/Genymobile/gnirehtet/issues/5?

**Comment by Biswa96** [comment] 2017-10-25 10:51
See also #40

**Closed** 2018-02-06 20:20 UTC
