### ISSUE TITLE
CAN YOU PLEASE HELP ME I HAVE BEEN TRYING TO SOLVE THIS ERROR

### ISSUE THREAD

**Issue by jhlalrinawma** [Genymobile/gnirehtet#291] opened 2020-04-17 08:54 UTC
Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\9

c:\9>gnirehtet install
2020-04-17 00:50:28.694 INFO Main: Installing gnirehtet client...
Performing Streamed Install
Success

c:\9>gnirehtet install
2020-04-17 00:51:07.686 INFO Main: Installing gnirehtet client...
Performing Streamed Install
Success

c:\9>gnirehtet run
2020-04-17 00:51:38.485 INFO Main: Checking gnirehtet client...
2020-04-17 00:51:38.485 INFO Main: Starting relay server on port 31416...
2020-04-17 00:51:38.485 INFO Relay: Relay server started
2020-04-17 00:51:38.625 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=24253, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=24253, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1132)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:934)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:626)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1717)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:557)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1156)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1127)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3978)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:544)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:175)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10815)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4812)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3065)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-04-17 00:51:38.742 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment] 2020-04-17 09:57
Duplicate of #5

**Closed by rom1v** 2020-04-17 09:57 UTC
