### ISSUE TITLE
Android O  can't start

### ISSUE THREAD

**Issue by bunnyblue** [Genymobile/gnirehtet#44] opened 2017-09-28 09:27 UTC
```
2017-09-28 17:23:11.470 INFO Main: Checking gnirehtet client...
2017-09-28 17:23:11.591 INFO Main: Starting relay server...
2017-09-28 17:23:11.591 INFO Main: Starting client...
2017-09-28 17:23:11.592 INFO Relay: Relay server started
Starting service: Intent { act=com.genymobile.gnirehtet.START }
Error: app is in background uid null
2017-09-28 17:23:11.700 ERROR Main: Cannot start client: Command adb ["shell", "am", "startservice", "-a", "com.genymobile.gnirehtet.START"] returned with value 255
^Z

```

**Comment by rom1v** [comment] 2017-09-28 10:22
Thank you for the report.

I have no Android O here, but I understand the cause.

I implemented a fix, could you test it, please?

[`gnirehtet-java-issue44.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-java-issue44.zip)
_SHA-256: fd33fd1f394150b62cc73f7f27f398120d74d48de2a5f59d78fe207ae95f62f0_
[`gnirehtet-rust-linux64-issue44.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-linux64-issue44.zip)
_SHA-256: 2742a817b5c3ebefdf814e77a66679ba5a02b8449122c5e50b04594676c1adaf_
[`gnirehtet-rust-win64-issue44.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-win64-issue44.zip)
_SHA-256: b2dd4fcc7909887563afd5d01dddf2e84590252b5fe14e5bd6d16c2e35b94b9f_
```

**Comment by rom1v** [comment] 2017-09-28 14:07
Could you try this new version on Android O, please?

[`gnirehtet-rust-linux64-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-linux64-androido.zip)
_SHA-256: 856c4ff779ff6d0d9813b24150e8ead672bf8c47ec8e0c2b6da031f9bc3b086e_
[`gnirehtet-rust-win64-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-win64-androido.zip)
_SHA-256: 78dcad6dbb265de26b7026de31f71be9081f333cfa808f85f365be38da73b97e_
[`gnirehtet-java-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-java-androido.zip)
_SHA-256: f650b750f0e56bc58e98bb6b87d62ac8a0bd7971562ed77454d21dc643f96180_

**Comment by rom1v** [comment] 2017-09-29 09:35
Fixed by 4e1490fe3070134e2200e0e8f936f718a9794959 and 8eb86832e29edc4032bec51461c4fb69bc48873a.

Binary including these commits here:
[`gnirehtet-rust-linux64-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-linux64-androido.zip)
_SHA-256: 1f9d942ad2fa6b0289dd58180657df86d05d40b8c5706e154175e87f1e12d5d9_
[`gnirehtet-rust-win64-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-rust-win64-androido.zip)
_SHA-256: 4b01e38e31efaa62df6cd65786d6a2e7bbb860876f7d3850f24da2a5f8e27750_
[`gnirehtet-java-androido.zip`](https://tmp.rom1v.com/gnirehtet/issue44/gnirehtet-java-androido.zip)
_SHA-256: a927cc2d2e131e649c53c7235a8585da050784699f846ecb5b62cb34c7851f2c_

(Uninstall any existing version first, with `gnirehtet uninstall`)

**Closed by rom1v** 2017-09-29 09:35 UTC
Labels: bug, enhancement

**Comment by Biswa96** [comment] 2017-09-29 09:48
Does this changes affect older versions of Android? Should I download app from your given link here or from the the link in releases v2.0?

**Comment by rom1v** [comment] 2017-09-29 09:54
@Biswa96 Those binaries are just built from the current `master` branch. They include changes that will be in the next release.

In particular, they include fixes for #42, #43 and #44.

They affect older versions of Android in that it fixes #42 and #43, and Gnirehtet now displays a permanent notification due to #44.

**Comment by Biswa96** [comment] 2017-09-29 13:31
But this new gnirehtet-rust-win64-androido.zip does not connect with Android 6.0.1 (while the older one v2.0 is running well). It stops after showing the following output and does not go further.

> C:\>gnirehtet.exe start
2017-09-29 18:57:07.933 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0
>C:\>gnirehtet.exe relay
2017-09-29 18:57:18.482 INFO Main: Starting relay server...
2017-09-29 18:57:18.486 INFO Relay: Relay server started
^C

**Comment by rom1v** [comment] 2017-09-29 14:03
@Biswa96, since it's not a release, I did not increment the versionCode, so you have to uninstall the old apk:

    gnirehtet uninstall

**Comment by Biswa96** [comment] 2017-10-06 15:11
@rom1v New version 2.1 also shows that previous error with Android 6.0.1
```
C:\>"E:\gnirehtet.exe" run
2017-10-06 20:36:56.055 INFO Main: Checking gnirehtet client...
2017-10-06 20:36:56.263 INFO Main: Starting relay server...
2017-10-06 20:36:56.263 INFO Main: Starting client...
2017-10-06 20:36:56.266 INFO Relay: Relay server started
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver } 
Broadcast completed: result=0
```

**Comment by rom1v** [comment] 2017-10-06 15:36
@Biswa96 I fail to reproduce your problem.

Here is what I do:
 - take a Nexus 5 with AOSP 6.0.1
 - run gnirehtet 2.0 (from Windows or Linux)
 - from Windows, run gnirehtet 2.1 (`gnirehtet.exe run`)

The client is reinstalled automatically, and it works as expected:

```
> gnirehtet.exe run
2017-10-06 17:33:21.326 INFO Main: Checking gnirehtet client...
2017-10-06 17:33:21.436 INFO Main: Installing gnirehtet client...
gnirehtet.apk: 1 file pushed.
        pkg: /data/local/tmp/gnirehtet.apk
Success
2017-10-06 17:33:23.139 INFO Main: Starting relay server...
2017-10-06 17:33:23.139 INFO Main: Starting client...
2017-10-06 17:33:23.139 INFO Relay: Relay server started
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0
2017-10-06 17:33:24.045 INFO TunnelServer: Client #0 connected
```

Does it work if you `gnirehtet uninstall` first?

Could you please paste the result of:

    adb shell dumpsys package com.genymobile.gnirehtet

?
