### ISSUE TITLE
Google Play can't download apps

### ISSUE THREAD

**Issue by akirayamamoto** [Genymobile/gnirehtet#106] opened 2018-04-03 23:44 UTC
This software works well for Whatsapp and Google Chrome but Google Play doesn't identify a connection and keep waiting. I would like to use reverse tethering to avoid data costs while installing apps. Google Photos also keeps waiting for a connection. Other than that gnirehtet works good.

Tks

**Comment by rom1v** [comment] 2018-04-04 07:41
Thank you for your report.

This is a duplicate of https://github.com/Genymobile/gnirehtet/issues/37.

**Closed by rom1v** 2018-04-04 07:41 UTC
