### ISSUE TITLE
Issue with using Torrent Clients when connected

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#29] opened 2017-04-29 18:30 UTC
When I use a Torrent Client on my Android Tablet when connected to my PC via gnirehtet, the downloads I start via the client eventually get slower/stop working.

**Comment by rom1v** [comment] 2017-06-19 15:23
Hi @Zero3K, I found a possible cause for this problem.

Could you test branch `issue29-totest`, please?

**Comment by Zero3K** [comment] 2017-06-19 23:03
It didn't help.

**Comment by rom1v** [comment] 2017-06-20 08:22
Thank you.

> It didn't help.
>
> EDIT: I think I have a different issue now.

Do you still have the initial issue?

> I think I have a different issue now. It disconnected from the relay server without me unplugging it/closing the adb.exe process.

I just reproduced that problem, `adb reverse` seems to fail at some point. When you restart it, it works again:

    adb reverse tcp:31416 tcp:31416

**Comment by Zero3K** [comment] 2017-06-20 18:27
1. I don't know. 
2. Is it fixable or not? 

On June 20, 2017, 4:22 AM, Romain Vimont wrote:
Thank you. 

It didn't help.


EDIT: I think I have a different issue now.


Do you still have the initial issue?


I think I have a different issue now. It disconnected from the relay server without me unplugging it/closing the adb.exe process.


I just reproduced that problem, adb reverse seems to fail at some point. When you restart it, it works again:

adb reverse tcp:31416 tcp:31416

**Comment by rom1v** [comment] 2017-06-20 18:55
>> Do you still have the initial issue?
> I don't know.

OK. Anyway, there was a problem, that I fixed in commit 91e7103a58938404bad951657ab2559b32043a1b. This may, or may not, be the cause of issue 29.

> Is it fixable or not?

I don't know, the `adb reverse` failure is not related to _gnirehtet_.

**Comment by Zero3K** [comment] 2017-06-23 14:12
How about having it try to reconnect if it gets disconnected while still plugged in?

**Comment by rom1v** [comment] 2017-06-23 14:19
> How about having it try to reconnect if it gets disconnected while still plugged in?

The device does not know if it is plugged in or not: it only knows if it may connect to the relay server (through the `adb reverse` tunnel).

The relay server detects that a client has been disconnected (the associated socket has been closed), but it does not know that it's because the `adb reverse` tunnel is down.

Detecting such a failure would require an active monitoring: the relay server would have to poll the result of `adb devices` and `adb reverse --list` commands every second (for instance), compare them, and reexecute the `adb reverse` command if something is wrong. Too heavyweight and ugly for such a workaround.

Are you often disconnected this way? It happened only once to me, and possibly because my adb daemon has been killed because I started an adb client with a different version (so I'm not even sure I had the problem).

**Comment by Zero3K** [comment] 2017-06-23 14:23
Yes, I am being disconnected that way quite often when using Vuze while connected to the relay server.

**Comment by Zero3K** [comment] 2017-07-03 16:42
Have you figured out how to fix the disconnecting issue or not?

**Comment by rom1v** [comment] 2017-07-03 19:19
No, I have not.

**Comment by Zero3K** [comment] 2017-08-10 22:19
Any news since then?

**Comment by rom1v** [comment] 2017-08-17 14:30
No news, in fact I can not even reproduce (I downloaded using LibreTorrent on Android).

**Comment by rom1v** [comment] 2017-10-16 09:20
Could you check if you still have this issue in the last release (both Java and Rust), please?

**Closed** 2018-02-06 20:15 UTC
