### ISSUE TITLE
Broadcast completed: result=0

### ISSUE THREAD

**Issue by RMcD94** [Genymobile/gnirehtet#146] opened 2018-10-12 04:58 UTC
2018-10-12 12:52:08.267 INFO Main: Checking gnirehtet client...
2018-10-12 12:52:08.267 INFO Main: Starting relay server...
2018-10-12 12:52:08.269 INFO Relay: Relay server started
2018-10-12 12:52:08.405 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0

I have been trying to get gnirehtet working on my work computer. I successfully used it on the same device in previous locations but here it is unsuccessful. I don't get the VPN pop up that I am used to asking to establish a connection.

ADB devices posts successfully, listing only one device. 

adb devices
List of devices attached
ad0a1603613712d224      device

Help would be appreciated.

**Comment by rom1v** [comment] 2018-10-12 05:06
Duplicate of https://github.com/Genymobile/gnirehtet/issues/117.

**Comment by rom1v** [comment] 2019-09-07 20:47
Fixed by f8681809a28a0073f791f0d9eae65da02ae73c3d.

**Closed by rom1v** 2019-09-07 20:47 UTC
Labels: nodialog
