### ISSUE TITLE
gnirehtet v2. 3 corrupted source code.

### ISSUE THREAD

**Issue by dking1330** [Genymobile/gnirehtet#239] opened 2019-11-02 07:21 UTC
Built on Android Studio successfully gnirehtet-v2. 2. 1; gnirehtet-v2. 2; gnirehtet-v2. 1 . Attention version gnirehtet v2. 3 is going but does not work! VPN on the phone does not rise.

**Comment by rom1v** [comment] 2019-11-02 07:41
Duplicate of your own issue #237.

> corrupted source code

:/

Follow the build instructions. Explain the problem with the logs you get.

The "no dialog" issue is well known on recent Android versions (check issues with label "nodialog") and is fixed on `master`.

**Closed by rom1v** 2019-11-02 07:41 UTC

**Comment by dking1330** [comment] 2019-11-02 14:24
you don't want to help. try to build 2.3 and make sure that it does not work.

**Comment by dking1330** [comment] 2019-11-02 14:28
I solved the build problem by deleting the project and updating all Studio components. Left a message in the log... but it seems it does not affect the run times.

--
11:59	Gradle sync started with single-variant sync

12:00	Project setup started

12:00	Source generation ended in 1 s 219 ms

12:00	Gradle sync finished in 40 s 63 ms

12:00	NDK Resolution Outcome: Project settings: Gradle model version=5.4.1, NDK version is UNKNOWN

12:02	Executing tasks: [:app:assembleRelease] in project C:\Gnirehtet\gnirehte\gnirehtet-2.3

12:03	Gradle build finished in 49 s 177 ms

12:03	Generate Signed APK
-------------------

**Comment by rom1v** [comment] 2019-11-02 14:58
> try to build 2.3

Try to build `master` instead.

And give the logs from `adb logcat` when you start gnirehtet, not the build logs.
