### ISSUE TITLE
how to access localhost from android mobile after connecting using gnirehtet

### ISSUE THREAD

**Issue by sant527** [Genymobile/gnirehtet#71] opened 2017-12-26 13:46 UTC
I am using this to do reverse tethering. I installed the apk on my android and after connecting my android phone by USB i ran ./gnirehtet run. And now i am able to acces internet on my android. 

But i have a server running on the localhost on my laptop. I can access it using 127.0.0.1:8000 from browser on laptop. How to access it on my android mobile. Which ip i have to use

**Comment by rom1v** [comment] 2017-12-26 14:47
The mapping is hardcoded: `10.0.2.2`.

**Comment by sant527** [comment] 2017-12-26 18:34
its very flickering. sometimes it shows no progress

**Comment by rom1v** [comment] 2017-12-30 21:02
Could you give more details?

**Comment by sant527** [comment] 2018-01-01 11:29
i am using django server

./manage.py runserver 10.0.0.2:8000

**Comment by sant527** [comment] 2018-01-01 11:36
I think there is some problem with the port:

I try 10.0.2.2 it opens my localhost

but if I localhost running on 8000 port then 10.0.2.2:8000 is not loading. 

It shows blank when i open in chrome

**Comment by rom1v** [comment] 2018-01-01 11:37
> i am using django server
>
>    ./manage.py runserver 10.0.0.2:8000

Your server must listen on localhost (127.0.0.1), and your client must access it through `10.0.2.2`.

**Comment by sant527** [comment] 2018-01-01 11:40
2018-01-01 17:09:29.761 INFO TcpConnection: 10.0.0.2:43916 -> 10.0.2.2:8000 Close
2018-01-01 17:09:29.761 INFO TcpConnection: 10.0.0.2:43917 -> 10.0.2.2:8000 Close
2018-01-01 17:09:29.761 INFO TcpConnection: 10.0.0.2:43918 -> 10.0.2.2:8000 Close
2018-01-01 17:09:29.848 INFO TcpConnection: 10.0.0.2:43919 -> 10.0.2.2:8000 Close

i think its sending the connection not able to recieve the incoming

**Comment by rom1v** [comment] 2018-01-01 12:16
> I think there is some problem with the port

I can't reproduce.

I started a simple http server on the computer listening on `127.0.0.1:8000`:

    python3 -m http.server --bind 127.0.0.1 8000

And I access `http://10.0.2.2:8000/` from the device, it works as expected.

**Comment by sant527** [comment] 2018-01-05 04:17
thats true. I think django is having some problem. I running a localserver on Django

**Comment by rom1v** [comment] 2018-02-06 20:07
OK, so for now I'm closing the issue, if you have new information, feel free to reopen.

**Closed by rom1v** 2018-02-06 20:07 UTC
