### ISSUE TITLE
Can't run it on S9+ (it worked well on S7Edge)

### ISSUE THREAD

**Issue by Leyharu** [Genymobile/gnirehtet#131] opened 2018-07-22 13:01 UTC
2018-07-22 14:59:07.139 INFO Main: Starting relay server...
2018-07-22 14:59:07.140 INFO Main: Checking gnirehtet client...
2018-07-22 14:59:07.142 INFO Relay: Relay server started
2018-07-22 14:59:07.261 INFO Main: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0
2018-07-22 14:59:09.720 INFO TunnelServer: Client #0 connected
thread 'main' panicked at 'Not an Ipv4 packet, version=6', src/relay/ipv4_packet_buffer.rs:38:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Appuyez sur une touche pour continuer...

**Comment by rom1v** [comment] 2018-07-22 13:08
Thank you for your report.

This is a duplicate ofhttps://github.com/Genymobile/gnirehtet/issues/69.
This is [fixed](https://github.com/Genymobile/gnirehtet/issues/69#issuecomment-405732946) on `master`.

**Closed by rom1v** 2018-07-22 13:08 UTC

**Comment by Leyharu** [comment] 2018-07-22 13:14
Thank you, how do I use it please?

**Comment by rom1v** [comment] 2018-07-22 13:16
You need to [build](https://github.com/Genymobile/gnirehtet/blob/master/DEVELOP.md#build) it manually.

**Comment by Leyharu** [comment] 2018-07-22 13:19
Could you please help me build it? I'm a beginner..

**Comment by Leyharu** [comment] 2018-07-22 13:33
I'm having this while building it:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_171 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Leyharu** [comment] 2018-07-22 13:41
Ok I manage to solve this issue, now I have this:

* What went wrong:
Execution failed for task ':relay-java:checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///C:/Users/btumd/Desktop/gnirehtet-master/relay-java/build/reports/checkstyle/main.html

**Comment by Leyharu** [comment] 2018-07-22 14:10
I installed Gradle and everything, but now my only issue is this:

Execution failed for task ':relay-java:checkstyleMain'.

After this it'll work

**Comment by rom1v** [comment] 2018-07-22 15:33
Check the logfile given in the error message.

**Comment by Leyharu** [comment] 2018-07-22 16:40
Could you please build it for me? I'm like so unexperienced...

**Comment by bafxyz** [comment] 2018-07-22 19:58
Same here, have problems with building 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.

**Comment by rom1v** [comment] 2018-07-22 21:46
See https://github.com/Genymobile/scrcpy/issues/3.

**Comment by bafxyz** [comment] 2018-07-22 21:54
Now i have another error
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The thing is what i have in path ANDROID_HOME, ANDROID_SDK and in local.properties sdk.dir=/Users/andrei.bunulu/Library/Android/sdk

**Comment by bafxyz** [comment] 2018-07-22 22:20
Ok i solved my issues by accepting android licences, downgrading java to version 8. After that "grudle build" ran successfully. After i did this "java -jar gnirehtet.jar run" and i see this
2018-07-23 00:15:44.895 I Gnirehtet: Checking gnirehtet client...
2018-07-23 00:15:44.895 I Gnirehtet: Starting relay server...
2018-07-23 00:15:44.926 I Relay: Relay server started
2018-07-23 00:15:45.015 I Gnirehtet: Starting client...
Broadcasting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
Broadcast completed: result=0
2018-07-23 00:15:45.167 I TunnelServer: Client #0 connected

And looks like everything should work, but i don't have internet on my android. Lock icon appeared and "Reverse tethering enabled" as well in notifications

What can be wrong?

**Comment by bafxyz** [comment] 2018-07-22 22:36
Nope i didn't reinstall it on my Oneplus6 device, the thing is what the apk from official zip for mac just worked on my OnePlus3 device with new gnirehtet.jar file. Probably reinstall will fix the issue on my Oneplus6 as well, can you explain how can i generate new apk? Thank you

**Comment by bafxyz** [comment] 2018-07-22 22:57
And another problem: So i have macbook with VPN which shares internet to my android phone with gnirehtet, whatismyip and speedtest are good here. Now i want to share this internet further from android device, so i'm creating portable Wifi hotspot on android, with another device connect to my android and i don't have internet on another device. In terminal i see this:
```
2018-07-23 00:56:42.498 W Router: Dropping invalid packet
2018-07-23 00:56:46.769 W Router: Dropping invalid packet
2018-07-23 00:56:47.798 W Router: Dropping invalid packet
2018-07-23 00:56:51.017 W Router: Dropping invalid packet
2018-07-23 00:56:53.084 W Router: Dropping invalid packet
2018-07-23 00:56:54.109 W Router: Dropping invalid packet
2018-07-23 00:57:00.266 W Router: Dropping invalid packet
2018-07-23 00:57:01.278 W Router: Dropping invalid packet
```

**Comment by rom1v** [comment] 2018-07-22 23:06
> Now i want to share this internet further from android device, so i'm creating portable Wifi hotspot on android, with another device connect to my android and i don't have internet on another device.

Sorry, it's not expected to work. https://github.com/Genymobile/gnirehtet/issues/126

**Comment by bafxyz** [comment] 2018-07-23 17:39
Ok, i did it today. Wors perfectly. The only issue is what root is required to share internet from android. And i installed "vpn hotspot tethering app" from Google play with green logo.

**Comment by Leyharu** [comment] 2018-07-27 12:17
Anyone knows how to fix the checkstyleMain issue?
