### ISSUE TITLE
Error: Requires permission android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by CoderBuck** [Genymobile/gnirehtet#5] opened 2017-04-06 09:33 UTC
XiaoMi4  Android 6.0  MIUI8
```
$ ./gnirehtet rt
Starting gnirehtet...
'adb' reverse tcp:31416 tcp:31416
'adb' shell am startservice -a com.genymobile.gnirehtet.START
Starting service: Intent { act=com.genymobile.gnirehtet.START }
Error: Requires permission android.permission.WRITE_SECURE_SETTINGS
'java' -jar relay.jar
2017-04-06 17:31:05.886 I Main: Starting server...
Stopping gnirehtet...
'adb' shell am startservice -a com.genymobile.gnirehtet.STOP
Starting service: Intent { act=com.genymobile.gnirehtet.STOP }
Error: Requires permission android.permission.WRITE_SECURE_SETTINGS
```

**Comment by rom1v** [comment] 2017-04-06 09:38
Arf, it seems that your `shell` user does not have this permission… It should have.

This requirement (a bit hacky) had been introduced in commit e7b84076a05effebf4aa2f47c9ad8ffff4fda382 (the commit message provides some details).

Does someone have an idea to get the same "restriction" without the `WRITE_SECURE_SETTINGS` permission?

**Comment by yashrajtalan** [comment] 2017-04-10 09:19
Have same issue with Xiaomi Redmi 3S Prime MIUI8 Android 6.0.1
Permissions granted to the app according to the phone are 'full network access' and 'view network connections'.

**Comment by rom1v** [comment] 2017-04-12 14:14
@CoderBuck @yashrajtalan Could you give me the permissions of your Android shell, please?

First, locate `Shell.apk`:

    $ adb shell pm list package -f com.android.shell
    package:/system/priv-app/Shell/Shell.apk=com.android.shell

Then pull it:

    adb pull /system/priv-app/Shell/Shell.apk

Finally, print its permissions:

    aapt d permissions Shell.apk

(`aapt` is available in `$ANDROID_SDK/build-tools/25.0.2/aapt`, or there is an `aapt` package in Debian)

Maybe we could find a better permission which works also for your devices ;-)

**Comment by CoderBuck** [comment] 2017-04-12 14:49
'''
$ adb shell pm list package -f com.android.shell
package:/system/priv-app/Shell/Shell.apk=com.android.shell

$ adb pull /system/priv-app/Shell/Shell.apk
adb: error: remote object 'D:/Develop/Git/Git/system/priv-app/Shell/Shell.apk' does not exist

'''

**Comment by CoderBuck** [comment] 2017-04-12 15:04
I am not familiar with this ;-0

**Comment by rom1v** [comment] 2017-04-12 15:13
@CoderBuck It seems you are using _git bash_ on _Windows_: http://stackoverflow.com/questions/16344985/how-do-i-pass-an-absolute-path-to-the-adb-command-via-git-bash-for-windows

Try with `cmd.exe` instead, since _git bash_ mangles pathes at some point.

**Comment by CoderBuck** [comment] 2017-04-12 15:17
thanks ;-)
```
package: com.android.shell
uses-permission: name='android.permission.SEND_SMS'
uses-permission: name='android.permission.CALL_PHONE'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-permission: name='android.permission.READ_CONTACTS'
uses-permission: name='android.permission.WRITE_CONTACTS'
uses-permission: name='android.permission.READ_CALENDAR'
uses-permission: name='android.permission.WRITE_CALENDAR'
uses-permission: name='android.permission.READ_USER_DICTIONARY'
uses-permission: name='android.permission.WRITE_USER_DICTIONARY'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_LOCATION_EXTRA_COMMANDS'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.BLUETOOTH'
uses-permission: name='android.permission.EXPAND_STATUS_BAR'
uses-permission: name='android.permission.DISABLE_KEYGUARD'
uses-permission: name='android.permission.REAL_GET_TASKS'
uses-permission: name='android.permission.CHANGE_CONFIGURATION'
uses-permission: name='android.permission.REORDER_TASKS'
uses-permission: name='android.permission.SET_ANIMATION_SCALE'
uses-permission: name='android.permission.SET_PREFERRED_APPLICATIONS'
uses-permission: name='android.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.WRITE_SECURE_SETTINGS'
uses-permission: name='android.permission.BROADCAST_STICKY'
uses-permission: name='android.permission.SET_DEBUG_APP'
uses-permission: name='android.permission.SET_PROCESS_LIMIT'
uses-permission: name='android.permission.SET_ALWAYS_FINISH'
uses-permission: name='android.permission.DUMP'
uses-permission: name='android.permission.SIGNAL_PERSISTENT_PROCESSES'
uses-permission: name='android.permission.KILL_BACKGROUND_PROCESSES'
uses-permission: name='android.permission.FORCE_BACK'
uses-permission: name='android.permission.BATTERY_STATS'
uses-permission: name='android.permission.INTERNAL_SYSTEM_WINDOW'
uses-permission: name='android.permission.INJECT_EVENTS'
uses-permission: name='android.permission.RETRIEVE_WINDOW_CONTENT'
uses-permission: name='android.permission.SET_ACTIVITY_WATCHER'
uses-permission: name='android.permission.READ_INPUT_STATE'
uses-permission: name='android.permission.SET_ORIENTATION'
uses-permission: name='android.permission.INSTALL_PACKAGES'
uses-permission: name='android.permission.MOVE_PACKAGE'
uses-permission: name='android.permission.CLEAR_APP_USER_DATA'
uses-permission: name='android.permission.DELETE_CACHE_FILES'
uses-permission: name='android.permission.DELETE_PACKAGES'
uses-permission: name='android.permission.ACCESS_SURFACE_FLINGER'
uses-permission: name='android.permission.READ_FRAME_BUFFER'
uses-permission: name='android.permission.DEVICE_POWER'
uses-permission: name='android.permission.INSTALL_LOCATION_PROVIDER'
uses-permission: name='android.permission.BACKUP'
uses-permission: name='android.permission.FORCE_STOP_PACKAGES'
uses-permission: name='android.permission.STOP_APP_SWITCHES'
uses-permission: name='android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY'
uses-permission: name='android.permission.GRANT_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.REVOKE_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.SET_KEYBOARD_LAYOUT'
uses-permission: name='android.permission.GET_DETAILED_TASKS'
uses-permission: name='android.permission.SET_SCREEN_COMPATIBILITY'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_MEDIA_STORAGE'
uses-permission: name='android.permission.INTERACT_ACROSS_USERS'
uses-permission: name='android.permission.INTERACT_ACROSS_USERS_FULL'
uses-permission: name='android.permission.CREATE_USERS'
uses-permission: name='android.permission.MANAGE_DEVICE_ADMINS'
uses-permission: name='android.permission.BLUETOOTH_STACK'
uses-permission: name='android.permission.GET_ACCOUNTS'
uses-permission: name='android.permission.RETRIEVE_WINDOW_TOKEN'
uses-permission: name='android.permission.FRAME_STATS'
uses-permission: name='android.permission.BIND_APPWIDGET'
uses-permission: name='android.permission.UPDATE_APP_OPS_STATS'
uses-permission: name='android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS'
uses-permission: name='android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.CHANGE_APP_IDLE_STATE'
uses-permission: name='android.permission.MOUNT_UNMOUNT_FILESYSTEMS'
uses-permission: name='android.permission.MOUNT_FORMAT_FILESYSTEMS'
uses-permission: name='android.permission.MODIFY_PHONE_STATE'
uses-permission: name='android.permission.REGISTER_CALL_PROVIDER'
uses-permission: name='android.permission.REGISTER_CONNECTION_MANAGER'
uses-permission: name='android.permission.REGISTER_SIM_SUBSCRIPTION'
uses-permission: name='android.permission.GET_APP_OPS_STATS'
```

**Comment by rom1v** [comment] 2017-04-12 15:28
OK so it declares using `android.permission.WRITE_SECURE_SETTINGS`.

Could you give the result of the following command, please:

    adb shell cat /proc/'$$'/status

**Comment by CoderBuck** [comment] 2017-04-12 15:43
Ok.
```
adb shell id

* daemon not running. starting it now on port 5037 *
* daemon started successfully *
uid=2000(shell) gid=2000(shell) groups=2000(shell),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0

adb shell cat /proc/'$$'/status

/system/bin/sh: cat: /proc/$$/status: No such file or directory
```

**Comment by rom1v** [comment] 2017-04-12 15:55
To summarize:
 1. `android.permission.WRITE_SECURE_SETTINGS` has [protection level "signature"](https://github.com/android/platform_frameworks_base/blob/b23fabf3fd0710a5e778f7befec0f962d9e569df/core/res/AndroidManifest.xml#L2105-L2106)
 2. sending the intent from shell leads to error `Requires permission android.permission.WRITE_SECURE_SETTINGS`
 3. shell declares using the permission `android.permission.WRITE_SECURE_SETTINGS`

One possibility is that `Shell.apk` is not signed with the same signature as the ROM. Which is very strange…

**Comment by rom1v** [comment] 2017-04-12 16:08
Could you replace `android.permission.WRITE_SECURE_SETTINGS` by `android.permission.WRITE_SETTINGS` (a permission with normal protection level) [here](https://github.com/Genymobile/gnirehtet/blob/0ec9fb956e0b99a627a30ddb0170baec040fcd80/app/src/main/AndroidManifest.xml#L19), build, and try again, please?

If it works, it suggests that the problem is related to `Shell.apk` signature…

**Comment by CoderBuck** [comment] 2017-04-13 01:45
error
```
Error: Requires permission android.permission.WRITE_SETTINGS
```

**Comment by rom1v** [comment] 2017-04-13 12:48
So you have a shell with no permissions… Can you find a permission listed from `Shell.apk` that does work?

**Comment by rom1v** [comment] 2017-04-14 19:42
What about:

    adb shell am startservice -a com.genymobile.gnirehtet.START --user 0
    adb shell am startservice -a com.genymobile.gnirehtet.START --user -2
    adb shell am startservice -a com.genymobile.gnirehtet.START --user -3

?

**Comment by rom1v** [comment] 2017-04-14 20:30
The result of this command may also be interesting:

    adb shell dumpsys package com.android.shell

**Comment by rom1v** [comment] 2017-04-18 11:45
@CoderBuck @yashrajtalan Could you please give the result of:

    adb shell dumpsys package com.android.shell

And also try [these commands](https://github.com/Genymobile/gnirehtet/issues/5#issuecomment-294222087).

Thank you :)

**Comment by yashrajtalan** [comment] 2017-04-25 14:20
The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following:
**USB debugging** -Debug mode when USB is connected
**Install via USB** -Allow installing apps via USB
**USB debugging (Security Settings)**- **Allow granting permissions** and simulating input via USB debugging

The first was already enabled, and I installed the apk file manually so I didn't need the second option.

I'm guessing the issue can be pinned down to the last option, which allows granting the necessary permissions. @CoderBuck please confirm.

Thank you @rom1v for this amazing app. This is a worthy free replacement for ReverseTethering NoRoot.

**Comment by CoderBuck** [comment] 2017-05-01 12:05
@rom1v @yashrajtalan  Sorry to replay late! @yashrajtalan you are right!

thanks a lot!

**Comment by rom1v** [comment] 2017-05-01 12:06
Great, thank you :+1: So I close the issue.

**Closed by rom1v** 2017-05-01 12:06 UTC

**Comment by Biswa96** [comment] 2017-10-28 07:23
@yashrajtalan Your procedure requires MI account in Xiaomi Redmi phones. You just remove `android.permission.WRITE_SECURE_SETTINGS` in manifest file (mentioned in #40).

**Comment by SonalDalal** [comment] 2018-10-11 10:48
@yashrajtalan, 
Thanks a lot, your solution worked for me.

**Comment by Mark-Joy** [comment] 2020-02-04 06:22
edit gnirehtet-run.cmd as below:

```
@echo off
adb shell "su -c 'setenforce 0'"
adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
adb shell "su -c 'setenforce 1'"
gnirehtet.exe run
pause

```
Note: if your device's SELInux mode is Permissive then you can remove setenforce commands

```
@echo off
adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
gnirehtet.exe run
pause
```

**Comment by stevelannist** [comment] 2020-03-03 15:31
I Have the same error 
![image](https://user-images.githubusercontent.com/56263133/75791162-1f0ba580-5da7-11ea-90e6-318fea26e5c9.png)

**Comment by elswerky** [comment] 2020-06-08 11:37
> edit gnirehtet-run.cmd as below:
> 
> ```
> @echo off
> adb shell "su -c 'setenforce 0'"
> adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
> adb shell "su -c 'setenforce 1'"
> gnirehtet.exe run
> pause
> ```
> 
> Note: if your device's SELInux mode is Permissive then you can remove setenforce commands
> 
> ```
> @echo off
> adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
> gnirehtet.exe run
> pause
> ```

thank you this worked for me on realme 2 pro ColorOs android pie and realmeUi android Q 
i made a script file to work on  Arch linux from your commands ,, here is its contents 

#!/bin/sh
adb shell "su -c 'setenforce 0'"
adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
adb shell "su -c 'setenforce 1'"
gnirehtet run

**Comment by elswerky** [comment] 2020-06-08 16:25
> edit gnirehtet-run.cmd as below:
> 
> ```
> @echo off
> adb shell "su -c 'setenforce 0'"
> adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
> adb shell "su -c 'setenforce 1'"
> gnirehtet.exe run
> pause
> ```
> 
> Note: if your device's SELInux mode is Permissive then you can remove setenforce commands
> 
> ```
> @echo off
> adb shell "su -c 'am start -a com.genymobile.gnirehtet.START -n com.genymobile.gnirehtet/.GnirehtetActivity'"
> gnirehtet.exe run
> pause
> ```thank you this worked with me on linux ,,i created a linux script for it and now my device realme 2 pro running ColorOs 6 android pie and realme Ui android 10 works fine

**Comment by ahmadabdelsattar** [comment] 2020-10-22 08:04
> What about:
> 
> ```
> adb shell am startservice -a com.genymobile.gnirehtet.START --user 0
> adb shell am startservice -a com.genymobile.gnirehtet.START --user -2
> adb shell am startservice -a com.genymobile.gnirehtet.START --user -3
> ```
> 
> ?

how to run them ?

**Comment by kachuy** [comment] 2020-10-26 05:40
> @CoderBuck @yashrajtalan Could you give the permissions of your Android shell, please?
> 
> First, locate `Shell.apk`:
> 
> ```
> $ adb shell pm list package -f com.android.shell
> package:/system/priv-app/Shell/Shell.apk=com.android.shell
> ```
> 
> Then pull it:
> 
> ```
> adb pull /system/priv-app/Shell/Shell.apk
> ```
> 
> Finally, print its permissions:
> 
> ```
> aapt d permissions Shell.apk
> ```
> 
> (`aapt` is available in `$ANDROID_SDK/build-tools/25.0.2/aapt`, or there is an `aapt` package in Debian)
> 
> Maybe we could find a better permission which works also for your devices ;-)

root@www:/mnt/c/scrcpy-win64-v1.16# aapt d permissions Shell.apk
package: com.android.shell
uses-permission: name='android.permission.SEND_SMS'
uses-permission: name='android.permission.CALL_PHONE'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-permission: name='android.permission.READ_CONTACTS'
uses-permission: name='android.permission.WRITE_CONTACTS'
uses-permission: name='android.permission.READ_CALENDAR'
uses-permission: name='android.permission.WRITE_CALENDAR'
uses-permission: name='android.permission.READ_USER_DICTIONARY'
uses-permission: name='android.permission.WRITE_USER_DICTIONARY'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_LOCATION_EXTRA_COMMANDS'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.BLUETOOTH'
uses-permission: name='android.permission.LOCAL_MAC_ADDRESS'
uses-permission: name='android.permission.EXPAND_STATUS_BAR'
uses-permission: name='android.permission.DISABLE_KEYGUARD'
uses-permission: name='android.permission.MANAGE_NETWORK_POLICY'
uses-permission: name='android.permission.MANAGE_USB'
uses-permission: name='android.permission.USE_RESERVED_DISK'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.REAL_GET_TASKS'
uses-permission: name='android.permission.CHANGE_CONFIGURATION'
uses-permission: name='android.permission.REORDER_TASKS'
uses-permission: name='android.permission.SET_ANIMATION_SCALE'
uses-permission: name='android.permission.SET_PREFERRED_APPLICATIONS'
uses-permission: name='android.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.WRITE_SECURE_SETTINGS'
uses-permission: name='android.permission.BROADCAST_STICKY'
uses-permission: name='android.permission.SET_DEBUG_APP'
uses-permission: name='android.permission.SET_PROCESS_LIMIT'
uses-permission: name='android.permission.SET_ALWAYS_FINISH'
uses-permission: name='android.permission.DUMP'
uses-permission: name='android.permission.SIGNAL_PERSISTENT_PROCESSES'
uses-permission: name='android.permission.KILL_BACKGROUND_PROCESSES'
uses-permission: name='android.permission.FORCE_BACK'
uses-permission: name='android.permission.BATTERY_STATS'
uses-permission: name='android.permission.PACKAGE_USAGE_STATS'
uses-permission: name='android.permission.INTERNAL_SYSTEM_WINDOW'
uses-permission: name='android.permission.INJECT_EVENTS'
uses-permission: name='android.permission.RETRIEVE_WINDOW_CONTENT'
uses-permission: name='android.permission.SET_ACTIVITY_WATCHER'
uses-permission: name='android.permission.READ_INPUT_STATE'
uses-permission: name='android.permission.SET_ORIENTATION'
uses-permission: name='android.permission.INSTALL_PACKAGES'
uses-permission: name='android.permission.MOVE_PACKAGE'
uses-permission: name='android.permission.CLEAR_APP_USER_DATA'
uses-permission: name='android.permission.CLEAR_APP_CACHE'
uses-permission: name='android.permission.DELETE_CACHE_FILES'
uses-permission: name='android.permission.DELETE_PACKAGES'
uses-permission: name='android.permission.ACCESS_SURFACE_FLINGER'
uses-permission: name='android.permission.READ_FRAME_BUFFER'
uses-permission: name='android.permission.DEVICE_POWER'
uses-permission: name='android.permission.INSTALL_LOCATION_PROVIDER'
uses-permission: name='android.permission.BACKUP'
uses-permission: name='android.permission.FORCE_STOP_PACKAGES'
uses-permission: name='android.permission.STOP_APP_SWITCHES'
uses-permission: name='android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY'
uses-permission: name='android.permission.GRANT_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.REVOKE_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS'
uses-permission: name='android.permission.SET_KEYBOARD_LAYOUT'
uses-permission: name='android.permission.GET_DETAILED_TASKS'
uses-permission: name='android.permission.SET_SCREEN_COMPATIBILITY'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_MEDIA_STORAGE'
uses-permission: name='android.permission.INTERACT_ACROSS_USERS'
uses-permission: name='android.permission.INTERACT_ACROSS_USERS_FULL'
uses-permission: name='android.permission.CREATE_USERS'
uses-permission: name='android.permission.MANAGE_DEVICE_ADMINS'
uses-permission: name='android.permission.MANAGE_COMPANION_DEVICES'
uses-permission: name='android.permission.ACCESS_LOWPAN_STATE'
uses-permission: name='android.permission.CHANGE_LOWPAN_STATE'
uses-permission: name='android.permission.READ_LOWPAN_CREDENTIAL'
uses-permission: name='android.permission.BLUETOOTH_STACK'
uses-permission: name='android.permission.GET_ACCOUNTS'
uses-permission: name='android.permission.RETRIEVE_WINDOW_TOKEN'
uses-permission: name='android.permission.FRAME_STATS'
uses-permission: name='android.permission.BIND_APPWIDGET'
uses-permission: name='android.permission.UPDATE_APP_OPS_STATS'
uses-permission: name='android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS'
uses-permission: name='android.permission.CHANGE_APP_IDLE_STATE'
uses-permission: name='android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST'
uses-permission: name='android.permission.MOUNT_UNMOUNT_FILESYSTEMS'
uses-permission: name='android.permission.MOUNT_FORMAT_FILESYSTEMS'
uses-permission: name='android.permission.MODIFY_PHONE_STATE'
uses-permission: name='android.permission.REGISTER_CALL_PROVIDER'
uses-permission: name='android.permission.REGISTER_CONNECTION_MANAGER'
uses-permission: name='android.permission.REGISTER_SIM_SUBSCRIPTION'
uses-permission: name='android.permission.GET_APP_OPS_STATS'
uses-permission: name='android.permission.MANAGE_APP_OPS_MODES'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.MANAGE_ACTIVITY_STACKS'
uses-permission: name='android.permission.START_TASKS_FROM_RECENTS'
uses-permission: name='android.permission.ACTIVITY_EMBEDDING'
uses-permission: name='android.permission.CONNECTIVITY_INTERNAL'
uses-permission: name='android.permission.CHANGE_COMPONENT_ENABLED_STATE'
uses-permission: name='android.permission.MANAGE_AUTO_FILL'
uses-permission: name='android.permission.NETWORK_SETTINGS'
uses-permission: name='android.permission.CHANGE_WIFI_STATE'
uses-permission: name='android.permission.SET_TIME'
uses-permission: name='android.permission.SET_TIME_ZONE'
uses-permission: name='android.permission.DISABLE_HIDDEN_API_CHECKS'
uses-permission: name='android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.CHANGE_OVERLAY_PACKAGES'
uses-permission: name='android.permission.RESTRICTED_VR_ACCESS'
uses-permission: name='android.permission.MANAGE_BIND_INSTANT_SERVICE'
uses-permission: name='android.permission.SET_HARMFUL_APP_WARNINGS'
uses-permission: name='android.permission.MANAGE_SENSORS'
uses-permission: name='android.permission.MANAGE_AUDIO_POLICY'
uses-permission: name='android.permission.MANAGE_CAMERA'
uses-permission: name='android.permission.ACCESS_INSTANT_APPS'
uses-permission: name='android.permission.MANAGE_BLUETOOTH_WHEN_PERMISSION_REVIEW_REQUIRED'
uses-permission: name='android.permission.MANAGE_WIFI_WHEN_PERMISSION_REVIEW_REQUIRED'
uses-permission: name='android.permission.WATCH_APPOPS'
uses-permission: name='android.permission.CONTROL_KEYGUARD'
root@www:/mnt/c/scrcpy-win64-v1.16# apt install adb

**Comment by lywit** [comment] 2020-12-02 15:11
It's stuck on "Starting: Intent { act=com.genymobile.gnirehtet.STOP cmp=com.genymobile.gnirehtet/.GnirehtetActivity }" for me
I don't see these two options on Samsung One UI 2.5:

Install via USB -Allow installing apps via USB
USB debugging (Security Settings)- Allow granting permissions and simulating input via USB debuggingInstall via USB -Allow

**Comment by rom1v** [comment] 2021-10-20 08:06
Please test enabling "security settings" in developer options: https://github.com/appium/appium/issues/13802#issuecomment-587802222

**Comment by rom1v** [comment] 2021-11-19 08:46
See https://github.com/Genymobile/gnirehtet/issues/302#issuecomment-973850470

**Comment by predi** [comment] 2022-10-17 07:23
On my OnePlus Nord 2T 5G (Android 12, OxygenOS 12.1), I also had to tick `Developer options > Disable permission monitoring` along with USB Debugging to get past a similar exception.

P.S.: apologies for reviving this old issue.

**Comment by flocsy** [comment] 2023-02-26 11:46
I had the same problem on OnePlus 8t, and the solution was to go to the Developer Settings on the phone and enable:
Developer Options > Apps > Disable permission monitoring

**Comment by rezyyyy** [comment] 2023-03-10 07:03
> The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following: **USB debugging** -Debug mode when USB is connected **Install via USB** -Allow installing apps via USB **USB debugging (Security Settings)**- **Allow granting permissions** and simulating input via USB debugging
> 
> The first was already enabled, and I installed the apk file manually so I didn't need the second option.
> 
> I'm guessing the issue can be pinned down to the last option, which allows granting the necessary permissions. @CoderBuck please confirm.
> 
> Thank you @rom1v for this amazing app. This is a worthy free replacement for ReverseTethering NoRoot.

![Screenshot_2023-03-09-20-44-36-545_com android settings](https://user-images.githubusercontent.com/49666136/224246144-1e4d45bc-b2c3-48d4-be85-354fb5111d50.jpg)


turning on the install via usb option requires an internet connection and currently am unable to do that. Is there a way to do this without having to connect to the internet. Note: the option is turned on in the screenshot but it automatically switches off after a couple of seconds..

**Comment by HoussemNasri** [comment] 2023-08-23 21:41
> I had the same problem on OnePlus 8t, and the solution was to go to the Developer Settings on the phone and enable:
Developer Options > Apps > Disable permission monitoring

The same solution worked for Oppo.

**Comment by maciejkrol18** [comment] 2023-10-07 12:56
> I had the same problem on OnePlus 8t, and the solution was to go to the Developer Settings on the phone and enable:
Developer Options > Apps > Disable permission monitoring


Also works on OnePlus Nord

**Comment by onyedikachi-david** [comment] 2023-12-11 14:23
> I had the same problem on OnePlus 8t, and the solution was to go to the Developer Settings on the phone and enable: Developer Options > Apps > Disable permission monitoring

This solution worked for me. Thanks.
Oppo CPH2269

**Comment by zanjie1999** [comment] 2024-08-07 01:18
Open this on Color OS can fix
打开禁止权限监控可以解决问题
<img width="411" alt="image" src="https://github.com/user-attachments/assets/61c17ca9-0c9a-407b-8b65-f79b3ab86891">

**Comment by lordofscripts** [comment] 2024-09-28 19:16
This:

> Developer Options > Apps > Disable permission monitoring

does not work on my device (RMX3241) a realme 8 (ColorOS)

**Comment by lordofscripts** [comment] 2024-09-28 19:17
> Open this on Color OS can fix 打开禁止权限监控可以解决问题 <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/16502567/355642166-61c17ca9-0c9a-407b-8b65-f79b3ab86891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NTExNzgsIm5iZiI6MTcyNzU1MDg3OCwicGF0aCI6Ii8xNjUwMjU2Ny8zNTU2NDIxNjYtNjFjMTdjYTktMGM5YS00MDdiLThiNjUtZjc5YjNhYjg2ODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE5MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNjY0MjJjN2ZlMTUzNzgwZGY3NDc3OGU3MmQxZTZhNGMyODhmZjUyYzlhNDIxMzNmMTcwNzliYWQ1ZDY2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wdk6NxP1GHTRUTPfphXGR94KRihOOgeQWc3XL36q2ds">

That's in Chinese, can't understand any of it. could you at least put the translated text?

**Comment by zanjie1999** [comment] 2024-09-29 09:42
> 禁止权限监控

may be "Disable permission monitoring"? translated with google. you can find it next of "ShortcutManager"

**Comment by Julioevm** [comment] 2024-10-10 11:16
> The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following: **USB debugging** -Debug mode when USB is connected **Install via USB** -Allow installing apps via USB **USB debugging (Security Settings)**- **Allow granting permissions** and simulating input via USB debugging
> 
> The first was already enabled, and I installed the apk file manually so I didn't need the second option.
> 
> I'm guessing the issue can be pinned down to the last option, which allows granting the necessary permissions. @CoderBuck please confirm.
> 
> Thank you @rom1v for this amazing app. This is a worthy free replacement for ReverseTethering NoRoot.

Any change to add this to the readme? It seems like a common issue with Xiaomi devices and would save a lot of people digging this information.

Thanks for the solution by the way.
