### ISSUE TITLE
Rust version panicks at start

### ISSUE THREAD

**Issue by sexybiggetje** [Genymobile/gnirehtet#119] opened 2018-06-20 11:41 UTC
I've accepted the vpn request, and immediatly it crashes.
However gnirehtet autostart does work fine :-)

> D:\gnirehtet-rust-win64>gnirehtet run
> 2018-06-20 13:36:57.650 INFO Main: Starting relay server...
> 2018-06-20 13:36:57.650 INFO Main: Checking gnirehtet client...
> 2018-06-20 13:36:57.652 INFO Relay: Relay server started
> 2018-06-20 13:36:58.605 INFO Main: Starting client...
> Broadcasting: Intent { act=com.genymobile.gnirehtet.START flg=0x400000 cmp=com.genymobile.gnirehtet/.GnirehtetControlReceiver }
> Broadcast completed: result=0
> 2018-06-20 13:37:01.724 INFO TunnelServer: Client #0 connected
> thread 'main' panicked at 'Not an Ipv4 packet, version=6', src/relay/ipv4_packet_buffer.rs:38:13
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by rom1v** [comment] 2018-06-20 12:16
Thank you for your report.

This is a duplicate of https://github.com/Genymobile/gnirehtet/issues/69.

**Closed by rom1v** 2018-06-20 12:16 UTC
