### ISSUE TITLE
stop gnirehtet after disconnected usb

### ISSUE THREAD

**Issue by AAide** [Genymobile/gnirehtet#379] opened 2021-03-26 12:58 UTC
Is it possible to stop gnirehtet just after removing the usb cable? Because Gnirehtet keeps a notification open with the message disconnected, but you have to press stop each time so that gnirehtet stops, because if they haven't, even if they have reactivated the wifi or the data, they will not work, until As long as you hit stop in the gnirehtet notification, it would be nice to stop gnirehtet instead of just considering that when the connection is lost it is just disconnected.

**Comment by rom1v** [comment] 2021-03-26 13:08
For now, no. Duplicate of #51.

**Closed by rom1v** 2021-03-26 13:08 UTC
