### ISSUE TITLE
Crashes: thread 'main' panicked at 'Removing an unknown connection', 

### ISSUE THREAD

**Issue by vasyugan** [Genymobile/gnirehtet#86] opened 2018-03-09 08:32 UTC
This happens during each use after some minutes

```
2018-03-09 09:23:46.000 INFO UdpConnection: 10.0.0.2:17666 -> 8.8.8.8:53 Close
2018-03-09 09:23:46.000 INFO UdpConnection: 10.0.0.2:22407 -> 8.8.8.8:53 Close
2018-03-09 09:23:46.000 INFO UdpConnection: 10.0.0.2:29966 -> 8.8.8.8:53 Close
2018-03-09 09:23:52.483 INFO TcpConnection: 10.0.0.2:47812 -> 172.217.20.72:443 Close
thread 'main' panicked at 'Removing an unknown connection', /checkout/src/libcore/option.rs:891:5

```

**Comment by rom1v** [comment] 2018-03-09 08:34
Thank you for your report.

This is a duplicate of https://github.com/Genymobile/gnirehtet/issues/61 and https://github.com/Genymobile/gnirehtet/issues/85.

This bug has already been fixed on the `dev` branch.

**Closed by rom1v** 2018-03-09 08:34 UTC
