### ISSUE TITLE
[Xiaomi Redmi 4 Prime] Server stuck, not asked for VPN

### ISSUE THREAD

**Issue by Broky** [Genymobile/gnirehtet#286] opened 2020-04-02 08:15 UTC
I am using the rust version.
USB-debugging and install per USB is activated. The installation went fine.
I start gnirehtet run on Windows and got stuck on the following lines, nothing asked on my phone.

2020-04-02 10:00:37.619 INFO Main: Starting relay server on port 31416...
2020-04-02 10:00:37.619 INFO Main: Checking gnirehtet client...
2020-04-02 10:00:37.619 INFO Relay: Relay server started
2020-04-02 10:00:37.729 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=12781, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at android.os.Parcel.readException(Parcel.java:1620)
        at android.os.Parcel.readException(Parcel.java:1573)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2869)
        at com.android.commands.am.Am.runStart(Am.java:875)
        at com.android.commands.am.Am.onRun(Am.java:359)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:100)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:332)

I saw some comments that i may be Xiaomi related, so i included my model.

**Comment by rom1v** [comment] 2020-04-02 08:42
Duplicate of #5.

**Closed by rom1v** 2020-04-02 08:42 UTC
